### ISSUE TITLE
mamFetch doesnt work anymore

### ISSUE THREAD

**Issue by User15362** [iotaledger/mam.js#106]
Hello
## Bug description
The mamFetch Function seems to not be working anymore. Opening a channel still works fine, but fetching the Message from the Channel doesn't work anymore and the mamFetch() returns undefined. (I know it returns that, when the Message can not be found, but the message is visible in the tangle explorer)

I am using the Iota Testnet and the same node to open and fetch the channel.

**Comment by obany** [comment]
How old is the message? the Tangle Explorer is connected to a permanode so has all messages, other nodes might have had the data pruned.

**Comment by User15362** [comment]
I am fetching the message ca 20 sec after attaching it to the tangle

**Comment by obany** [comment]
I just tested using the `simple` and `listen` examples from the repo using https://api.hornet-1.testnet.chrysalis2.com/ it all worked without problem.

simple
```
Seed: AAYHJREVLAGOIKDEPWQA9WOURDRFZZFUWJSADNPLAHX9PWLSWDVEQJTFHUTMOVVCHUXGPFOTRACDFLXUB
Address: EQXYVAEXUQDOUAEWXEWFLVFOOH9XYIMQFMCZVHSFHXGWAGMLMKGQFU9DHKALHXVWSN9BCWHXAJEHXYCVN
Root: FUCGYVSFNLHZW9PJXQN9TAFXFVKIJJPOMBXFS9TUAXLV9JDPZCQKNCUBCHTYIZVHDAQRUDPITIGLNPWHF
NextRoot: XIWIPXTSMOTGWABCQVMPWHBVHSCVJQUULJIUCLVJRXPPOA9GJNBGLEQR9XINZGALKFWSRTUMLLOBOHZDU
Decoded NextRoot XIWIPXTSMOTGWABCQVMPWHBVHSCVJQUULJIUCLVJRXPPOA9GJNBGLEQR9XINZGALKFWSRTUMLLOBOHZDU
Decoded Message RBTC9D9DCDEAWBKBWBEAFCCDFD9DSCFA
Attaching to tangle, please wait...
Message Id 81feee2558ff613776bf67d2fd612b0a159a4d075809136a8abb6899ee13cca2
You can view the stored message here https://explorer.iota.org/testnet/message/81feee2558ff613776bf67d2fd612b0a159a4d075809136a8abb6899ee13cca2
You can view the mam channel here https://explorer.iota.org/testnet/streams/0/FUCGYVSFNLHZW9PJXQN9TAFXFVKIJJPOMBXFS9TUAXLV9JDPZCQKNCUBCHTYIZVHDAQRUDPITIGLNPWHF/restricted/MYKEY
Fetching from tangle, please wait...
Fetched Root FUCGYVSFNLHZW9PJXQN9TAFXFVKIJJPOMBXFS9TUAXLV9JDPZCQKNCUBCHTYIZVHDAQRUDPITIGLNPWHF
Fetched Hello MAM World!
Fetched Next Root XIWIPXTSMOTGWABCQVMPWHBVHSCVJQUULJIUCLVJRXPPOA9GJNBGLEQR9XINZGALKFWSRTUMLLOBOHZDU 
done
```

listen
```
Running in background
Fetching from tangle, please wait...
Fetched Hello MAM World!
```

explorer: https://explorer.iota.org/testnet/streams/0/FUCGYVSFNLHZW9PJXQN9TAFXFVKIJJPOMBXFS9TUAXLV9JDPZCQKNCUBCHTYIZVHDAQRUDPITIGLNPWHF/restricted/MYKEY

**Comment by User15362** [comment]
Thank you for your help :) Looks like i used a node that seems to instantly prune the messages (https://api.hornet-0.testnet.chrysalis2.com). It works with the one you used, thanks alot!
