### ISSUE TITLE
Slow execution of the mamAttach function

### ISSUE THREAD

**Issue by sdellava** [iotaledger/mam.js#14]
This issue is related to the Chrysalis version of the MAM.js lib

I've done many test with the new lib and I've noted that the mamAttach is 3 time slower than the previous version in mainnet. Considering that I've used the testnet, it is a very negative behaviour.

I'd like to move to Streams, but I've lot of code written in node.js and at the moment the stream.js lib is not available.

I've analyzed the cause of the slowdown and I suppose it is caused by the message enconding.

The encoding is done in the client.ts: https://github.com/iotaledger/mam.js/blob/chrysalis/src/mam/client.ts

at line 36 the message payload is converted in byte:   data.set(Converter.utf8ToBytes(mamMessage.payload), 1 + tagLength);
   
This cause the us of une byte of the transaction for each character of the payload leading to a higher MWM required to the pow process.

I guess that the binary encoding will save lot of space reducing the required pow.

**Comment by obany** [comment]
As of this commit https://github.com/iotaledger/mam.js/commit/fadac302d5e234d1498d4e23dc50bf0467e8e197 the trytes are packed into 5bit to save space, but you will find this is an issue with the nodes themselves not mam.js, try just sending an indexation packet to a node and you will see the same problem.

You should open an issue on the node software repos.
